### ISSUE TITLE
Run environment

### ISSUE THREAD

**Issue by lyf7115** [takanori-fujiwara/multidr#1]
Hi,
I'm very interesting in this  work,but I only have Windows supports.
How could I run this code in Win10.

**Comment by takanori-fujiwara** [comment]
Hi, currently MulTiDR only supports macOS and Linux. In the future, there is a possibility to support Windows. But, for now, please try to use Linux with a virtual machine environment on your windows.

**Comment by takanori-fujiwara** [comment]
Hi, finally, I supported Windows.
