### ISSUE TITLE
Unable to run on Windows because of uvloop dependency

### ISSUE THREAD

**Issue by JRitmeester** [takanori-fujiwara/multidr#2]
Dear authors,

I was excited to try your application for my work with high-dimensional EMG data, but unfortunately your dependency on the server's use of "uvloop" does not allow me to use it on Windows, because the library does not support Windows itself. As far as I can tell, there is [only one line where the dependency is used](https://github.com/takanori-fujiwara/multidr/blob/7df887ede573af4aaad24fea19dca456d7a52ff1/ui/server/ws_server.py#L186). Would it be possible to substitute this with something that is more cross-platform friendly?

I'd be happy to hear from you.

**Comment by takanori-fujiwara** [comment]
Hi, thank you for pointing out this issue. Several months ago I tried to support Windows. But, I still was not able to find enough time to support Windows (Windows is quite different from UNIX/Linux, and supporting it needs a lot of effort for preparing the environment, testing, etc).  Realistically, I cannot find time to support Windows for the next few months. 

So, if you want to try the web app soon, please try to use Linux with a virtual machine environment on your windows.

**Comment by takanori-fujiwara** [comment]
Hi, finally, I supported Windows.
